### ISSUE TITLE
manuscript typos

### ISSUE THREAD

**Issue by messersc** [BIMSBbioinfo/maui#1]
Hi,

I was reading the preprint and just wanted to let you know some typos to fix for the next revision of the manuscript :)

* adn
* deleteions

Clemens

**Comment by messersc** [comment]
spanend -> spanned

**Comment by jonathanronen** [comment]
Thanks, @messersc :beers:

**Comment by messersc** [comment]
https://github.com/BIMSBbioinfo/maui/blob/master/maui/autoencoders_architectures.py#L300

should be `latent_dim`

**Comment by jonathanronen** [comment]
Indeed. thanks, Clemens!

**Comment by messersc** [comment]
"falce positive rate" in `utils.py`

**Comment by jonathanronen** [comment]
Thanks again, @messersc . Closing this issue as it seems you haven't found anything new in a while!
