### ISSUE TITLE
Include trained model from preprint and release all input data

### ISSUE THREAD

**Issue by messersc** [BIMSBbioinfo/maui#2]
Hi,

I was following the vignette and noticed that it makes some simplifications compared to the manuscript.

From what I can see, the repo is currently missing the smoothed mutation input data, which means one cannot train the model as you did for the preprint. This would be quite nice, of course, as for instance the Kaplan-Meyer analysis yields no difference between clusters going by the vignette.

Also, for reproducibility, I think it would be good to include the final model used in the preprint.

Kind regards,
Clemens

**Comment by jonathanronen** [comment]
Hey Clemens

Yes, we made the vignette a toy version of the full analysis in the paper. You're right of course that making the fuller data set available would make it easier to reproduce. We'll try to get to it soon. In the meanwhile, I hope there's enough information in the paper and the documentation for you to be able to reproduce it with some extra work. Let me know of course if you have any questions about that.

Best,
J.
