### ISSUE TITLE
Sigmoid activation with inputs out of [0,1] range

### ISSUE THREAD

**Issue by messersc** [BIMSBbioinfo/maui#8]
Hi Jona @jonathanronen,

I was having another look at maui and now I have another question :) 

As the final activation function, the model uses a sigmoid, so all output values will fall between 0 and 1.
On the other hand, inputs from RNA-seq are scaled, and at least in the vignette that leads to values outside of this range.

Is there any theoretical justification for this choice or did you choose it because it performs well in this setting? Did you try anything else, like the MinMaxScaler to start with [0,1] intervals for each feature?

Best wishes and thanks!
Clemens

**Comment by jonathanronen** [comment]
Thanks for your question, @messersc . You're right of course, it's not an ideal output function from a reconstruction perspective, but it works well enough for latent space learning. I would love to hear about any results you get from playing with this!

Best wishes of a safe and cozy lock-down-x-mas-new-year,
J.
