### ISSUE TITLE
return factor importance value rather than filtering them

### ISSUE THREAD

**Issue by borauyar** [BIMSBbioinfo/maui#9]
Hey Jona. 

Could you maybe provide an option to return the actual R^2 values of each LF from the function `maui.utils.filter_factors_by_r2` rather than returning a filtered matrix. Or, could it be made an option? 
The user could sort LFs by this value for downstream applications. When filtered, importance scores/rankings are lost.

**Comment by jonathanronen** [comment]
Now available via `maui.utils.r2_score_factors(z, x)`. Will gladly take suggestions for a better API? :)
